### ISSUE TITLE
Telegram Channel Support

### ISSUE THREAD

**Issue by louanfontenele** [eikowagenknecht/lootscraper#107]
### Is your feature request related to a problem? Please describe.

Adicionar suporte para adicionar bot aos Canais do Telegram.

### Describe the solution you'd like

Unfortunately when I add the bot to the channel, I can't use the commands.

**Comment by eikowagenknecht** [comment]
Just to understand: You mean you added the bot to a group chat and it doesn't react to the commands inside this group chat?

**Comment by eikowagenknecht** [comment]
I'll have a look at it

**Comment by louanfontenele** [comment]
> I'll have a look at it

thank you.

**Comment by eikowagenknecht** [comment]
Commands are not supported in a channel by the Telegram Python bot. This is correct, because channels should only contain public information. Commands should be sent to the bot in a private message.

I added a new command to add channels with #108. But only the admin can add new channels for now (so in the public instance that's running here, that's me).

**Comment by eikowagenknecht** [comment]
You can find the new official channels in the readme: https://github.com/eikowagenknecht/lootscraper
