### ISSUE TITLE
Image changes

### ISSUE THREAD

**Issue by IPFizzy** [eikowagenknecht/lootscraper#213]
### Is your feature request related to a problem? Please describe.

Posts could look a lot better (at least via Discord)

### Describe the solution you'd like

It would be great if the provided images included the banner for the game / reward the post is about to replace the bird image and rearrange the images to make it the main focal point. (_Big bonus if it's possible to bold sections of information as show below_)

Reference on my discord bot,
Before:
![image](https://github.com/eikowagenknecht/lootscraper/assets/138335528/7c9d9461-3707-4433-8db9-5097a390a9cf)
After:
![image](https://github.com/eikowagenknecht/lootscraper/assets/138335528/15d96b39-50d3-4a18-a65d-efe68f2ab0e3)

**Comment by eikowagenknecht** [comment]
Since there is no official Discord integration yet: Which bot are you talking about? My guess is that it picks up the default favicon of my domains (the bird image).

In my RSS feed the correct image is included already (and also the bold text):

![image](https://github.com/eikowagenknecht/lootscraper/assets/1475672/4eb7eff0-f59d-42de-8b08-a304cb0b19b3)

So it seems that this should be directed to the person who wrote the discord bot.

**Comment by IPFizzy** [comment]
Huh, must be an issue on my end then. Thanks!
